name: Super Linter and Pages Deploy

on:
  push:
    branches: [main]

jobs:
  super-linter:
    runs-on: ubuntu-latest
    name: Run Super Linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Run linter
        uses: github/super-linter@v5
        with:
          validation-matrix: 'javascript,typescript,html,css'
          fail-on-error: false
  pages-deploy:
    runs-on: ubuntu-latest
    needs: [super-linter]
    name: Deploy to GitHub Pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
